version: "3.9"

services:
  clonebot:
    image: kerensekali/clonebot:latest
    container_name: clonebot
    environment:
      - telegram_token=${telegram_token}
      - user_ids=${user_ids}
      - group_ids=${group_ids}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
